apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: onlyoffice-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.onlyoffice.hostname  }}`)
      middlewares:
        - name: rewrite-to-https
          namespace: {{ .Release.Namespace }}
      services:
        - kind: Service
          name: onlyoffice
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: 80
          scheme: http
