apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: onlyoffice-http
  namespace: {{ .Release.Namespace }}
spec:
  entrypoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.onlyoffice.hostname  }}`)
      middlewares:
        - name: redirect-https
          namespace: {{ .Release.Namespace }}
      services:
        - kind: Service
          name: onlyoffice
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: 8069
          scheme: http
