apiVersion: v1
kind: Service
metadata:
  name: onlyoffice
  namespace: {{ .Release.Namespace }}
  labels:
    app: onlyoffice
spec:
  selector:
    app: onlyoffice
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
