# Image configuration
image:
  repository: docker.bemade.org/bemade/odoo-openapi  # Container image repository
  tag: latest                # Container image tag
  pullPolicy: IfNotPresent   # Image pull policy
imagePullSecrets:
  - name: docker.bemade.org

# Ingress configuration
ingress:
  enabled: true # Set to true to enable ingress
  className: "nginx"         # Ingress class name
  hostnames:
    - openapi.odoo.bemade.org

certManager:
  enabled: true
  clusterIssuer: letsencrypt-dns

# Odoo API Configuration
odoo:
  url: ""    # Odoo server URL
  db: ""                 # Odoo database name
  user: ""              # Odoo username
  password: ""               # Odoo password (will be stored in a secret)

# API Configuration
api:
  key: ""                   # API key for authentication (will be stored in a secret)
  port: 8000                # Port to expose the API on
