apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-operator.fullname" . }}
  labels:
    {{- include "odoo-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "odoo-operator.selectorLabels" . | nindent 4 }}
