{{- if .Values.openclaw.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openclaw-https
  namespace: {{ .Release.Namespace }}
  labels:
    app: openclaw
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.openclaw.hostname }}`)
      priority: 10
      services:
        - kind: Service
          name: openclaw
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: {{ .Values.openclaw.port }}
          scheme: http
      middlewares:
        - name: openclaw-headers
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: openclaw-cert
{{- end }}
