image: odoo:18.0
gitProject:
  repository: # Optional
  branch: # Optional
  sshSecret: # Optional secret name containing the SSH key
imagePullSecret: docker.bemade.org
adminPassword:
replicas: 1
resources:
  requests:
    cpu: 200m
    memory: 250Mi
  limits:
    cpu: 2000m
    memory: 2Gi
filestore:
  storageSize: 2Gi
  storageClass: longhorn
ingress:
  hosts:
    - odoo.bemade.org
  issuer: letsencrypt
configOptions:
  workers: "2"
  limit_time_real: "600"
  limit_time_cpu: "600"
  addons_path: "/mnt/extra-addons,/mnt/enterprise-addons"
gitProject:
  repository: "" # Git repository URL, in git@ format if SSH is used
  branch: "" # Optional, default is "main"
  sshSecret: "" # Optional secret name containing the SSH key
  size: "" # Optional, default is "1Gi"
  storageClass: "" # Optional, default is cluster's default