# Deployment for the Odoo production server with WebSocket support
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: {{ .Release.Namespace }}
  labels:
    app: odoo-{{ .Values.odoo.hostname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-{{ .Values.odoo.hostname }}
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: odoo-{{ .Values.odoo.hostname }}
    spec:
      {{- if .Values.odoo.imageRegistry.url }}
      imagePullSecrets:
        - name: registry-secret
      {{- end }}
      volumes:
        - name: {{ .Values.odoo.hostname }}-filestore
          persistentVolumeClaim:
            claimName: {{ .Values.odoo.hostname }}-filestore-pvc
        - name: odoo-conf
          configMap:
            name: odoo-conf
      initContainers:
        - name: init-permissions
          image: {{ .Values.odoo.image }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: ["sh", "-c", "chown -R odoo:odoo /var/lib/odoo"]
          volumeMounts:
            - name: {{ .Values.odoo.hostname }}-filestore
              mountPath: /var/lib/odoo
            - name: odoo-conf
              mountPath: /etc/odoo
      containers:
        - name: odoo-{{ .Values.odoo.hostname }}
          image: {{ .Values.odoo.image }}
          ports:
            - containerPort: 8069  # Odoo HTTP
            - containerPort: 8072  # WebSocket port
          volumeMounts:
            - name: {{ .Values.odoo.hostname }}-filestore
              mountPath: /var/lib/odoo  # Mounting the filestore
            - name: odoo-conf
              mountPath: /etc/odoo
          env:
            - name: HOST
              value: {{ .Release.Name }}-postgresql
            - name: PORT
              value: "5432"
            - name: USER
              value: "odoo"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: odooPassword
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "4"
              memory: "8Gi"
          readinessProbe:
            httpGet:
              path: /web/health
              port: 8069
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /web/health
              port: 8069
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 6
      # Apply custom affinity if defined, otherwise use default worker node affinity
      affinity:
      {{- if .Values.odoo.affinity }}
        {{- toYaml .Values.odoo.affinity | nindent 8 }}
      {{- else }}
        # Default affinity to target worker nodes
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      {{- end }}
