apiVersion: v1
kind: Service
metadata:
  name: odoo-{{ .Values.odoo.production.hostname }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: odoo-{{ .Values.odoo.production.hostname }}
spec:
  selector:
    app: odoo-{{ .Values.odoo.production.hostname }}
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069  # HTTP port
      name: http
    - protocol: TCP
      port: 8072
      targetPort: 8072  # WebSocket port
      name: websocket
      appProtocol: kubernetes.io/ws
