odoo:
  image: "odoo:17"
  domain: "odoo.bemade.org"
  production:
    hostname: "demo"
  staging:
    - hostname: "stg1"
      productionDatabase: "odoo"
      storageClassName: "non-replicated-storage"
    - hostname: "stg2"
      productionDatabase: "odoo"
      storageClassName: "non-replicated-storage"
  filestore:
    size: ""
    storageClassName: "longhorn"
  db:
    size: ""
  ingress:
    enabled: true
    tlsSecretName: "odoo-tls-secret"
    clusterIssuer: "letsencrypt-dns"
  masterPassword: "$00p3rP4ssW0rD!"
