odoo:
  image: "odoo:17"
  domain: "demo.odoo.bemade.org"
  staging:
    enabled: false
    replicaCount: 2
  filestore:
    size: ""
    storageClassName: ""
  db:
    size: ""
  ingress:
    enabled: true
    tlsSecretName: "odoo-tls-secret"
    clusterIssuer: "letsencrypt-dns"
