odoo:
  image: "odoo:17"
  domain: "odoo.bemade.org"
  production:
    hostname: "demo"
  staging:
    - hostname: "stg1"
      productionDatabase: "odoo"
      storageClassName: ""
    - hostname: "stg2"
      productionDatabase: "odoo"
      storageClassName: ""
  filestore:
    size: ""
    storageClassName: ""
  db:
    size: ""
  ingress:
    enabled: true
    tlsSecretName: "odoo-tls-secret"
    clusterIssuer: "letsencrypt-dns"
