apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-pgvector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgres-pgvector.name" . }}
    helm.sh/chart: {{ include "postgres-pgvector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "postgres-pgvector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: 5432
