apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-openapi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoo-openapi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "odoo-openapi.selectorLabels" . | nindent 4 }}
