{{- if .Values.odoo.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-http-redirect
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web  # Listen on HTTP (port 80)
    traefik.ingress.kubernetes.io/router.middlewares: odoo-http-to-https
spec:
  rules:
    - host: {{ .Values.odoo.production.hostname }}.{{ .Values.odoo.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odoo-{{ .Values.odoo.production.hostname }}
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: odoo-http-to-https
  namespace: {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true  # Sends a 301 Moved Permanently

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /websocket

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-https
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure  # Listen on HTTPS (port 443)
    traefik.ingress.kubernetes.io/router.tls: "true"             # Enable TLS
spec:
  rules:
    - host: {{ .Values.odoo.production.hostname }}.{{ .Values.odoo.domain }}
      http:
        paths:
          # HTTP traffic
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odoo-{{ .Values.odoo.production.hostname }}
                port:
                  number: 8069
          # WebSocket traffic
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: odoo-{{ .Values.odoo.production.hostname }}
                port:
                  number: 8072
            annotations:
              traefik.ingress.kubernetes.io/router.middleware: websocket-strip-prefix@kubernetescrd
  tls:
    - hosts:
        - {{ .Values.odoo.production.hostname }}.{{ .Values.odoo.domain }}
      secretName: {{ .Values.odoo.ingress.tlsSecretName }}

{{- end}}