{{- if .Values.odoo.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-odoo
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.odoo.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "720"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "720"
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
      proxy_cookie_flags session_id samesite=lax secure;  # requires nginx 1.19.8
spec:
  ingressClassName: nginx
  rules:
    # Production
    - host: {{ .Values.odoo.production.hostname }}.{{ .Values.odoo.domain }}
      http:
        paths:
          # HTTP traffic
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odoo-{{ .Values.odoo.production.hostname }}
                port:
                  number: 8069
          # WebSocket traffic
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: odoo-{{ .Values.odoo.production.hostname }}
                port:
                  number: 8072
                appProtocol: kubernetes.io/ws

    # Staging (if applicable)
    {{- range .Values.odoo.staging }}
    - host: {{ .hostname }}.{{ $.Values.odoo.domain }}
      http:
        paths:
          # HTTP traffic
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odoo-{{ .hostname }}
                port:
                  number: 8069
          # WebSocket traffic
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: odoo-{{ .hostname }}
                port:
                  number: 8072
    {{- end }}
  tls:
    - hosts:
        - {{ .Values.odoo.production.hostname }}.{{ .Values.odoo.domain }}
        {{- range .Values.odoo.staging }}
        - {{ .hostname }}.{{ $.Values.odoo.domain }}
        {{- end }}
      secretName: {{ .Values.odoo.ingress.tlsSecretName }}
{{- end }}