{{- if .Values.odoo.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-odoo-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.odoo.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.odoo.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-odoo-service
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.odoo.ingress.host }}
      secretName: {{ .Values.odoo.ingress.tlsSecretName }}
{{- end }}
