apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: {{ .Release.Namespace }}
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      volumes:
        - name: odoo-filestore
          persistentVolumeClaim:
            claimName: odoo-filestore-pvc
        - name: init-db-script
          configMap:
            name: init-db-script
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 101:101 /var/lib/odoo"]
          volumeMounts:
            - name: odoo-filestore
              mountPath: /var/lib/odoo
        - name: init-db-user
          image: postgres:16.1
          command: ["/bin/bash", "/scripts/init-db-user.sh"]
          env:
            - name: HOST
              value: kubegres
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: superUserPassword
          volumeMounts:
            - name: init-db-script
              mountPath: /scripts
      containers:
        - name: odoo
          image: {{ .Values.odoo.image }}
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: odoo-filestore
              mountPath: /var/lib/odoo  # Mounting the filestore
          env:
            - name: HOST
              value: kubegres
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
