# Deployment for the Odoo production server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: {{ .Release.Namespace }}
  labels:
    app: odoo-{{ .Values.odoo.production.hostname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-{{ .Values.odoo.production.hostname }}
  template:
    metadata:
      labels:
        app: odoo-{{ .Values.odoo.production.hostname }}
    spec:
      {{- if .Values.odoo.imageRegistry.url }}
      imagePullSecrets:
        - name: registry-secret
      {{- end }}
      volumes:
        - name: {{ .Values.odoo.production.hostname }}-filestore
          persistentVolumeClaim:
            claimName: {{ .Values.odoo.production.hostname }}-filestore-pvc
        - name: init-db-script
          configMap:
            name: init-db-script
        - name: git-pull-addons
          configMap:
            name: git-pull-addons
        - name: repo
          persistentVolumeClaim:
            claimName: {{ .Values.odoo.production.hostname }}-git-repos-pvc
        - name: extra-addons
          persistentVolumeClaim:
            claimName: {{ .Values.odoo.production.hostname }}-extra-addons-pvc
        {{- if .Values.odoo.gitProject.sshKeySecret }}
        - name: ssh-key
          secret:
            secretName: {{ .Values.odoo.gitProject.sshKeySecret }}
            items:
              - key: ssh-privatekey
                path: ssh-privatekey
              - key: ssh-publickey
                path: ssh-publickey
        {{- end }}
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 101:101 /var/lib/odoo"]
          volumeMounts:
            - name: {{ .Values.odoo.production.hostname }}-filestore
              mountPath: /var/lib/odoo
        - name: init-db-user
          image: postgres:16.1
          command: ["/bin/bash", "/scripts/init-db-user.sh"]
          env:
            - name: HOST
              value: kubegres
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: superUserPassword
          volumeMounts:
            - name: init-db-script
              mountPath: /scripts
        - name: git-clone
          image: "alpine/git"
          env:
            - name: REPO_URL
              value: {{ .Values.odoo.gitProject.url | quote }}
            - name: BRANCH
              value: {{ .Values.odoo.production.branch | quote }}
            - name: COMMIT
              value: {{ .Values.odoo.production.commit | quote }}
            {{- if .Values.odoo.enterprise }}
            - name: ENTERPRISE_BRANCH
              value: {{ .Values.odoo.enterprise.branch | quote }}
            - name: ENTERPRISE_COMMIT
              value: {{ .Values.odoo.enterprise.commit | quote }}
            {{- end }}
          command:
            - "sh"
            - "-c"
            - |
              cp /scripts/git-pull-addons.sh ~/git-pull-addons.sh && chmod +x ~/git-pull-addons.sh && ~/git-pull-addons.sh
          volumeMounts:
            - name: repo
              mountPath: /mnt/repo
            - name: extra-addons
              mountPath: /mnt/extra-addons
            - name: git-pull-addons
              mountPath: /scripts
            - name: ssh-key
              mountPath: /mnt/secrets
      containers:
        - name: odoo-{{ .Values.odoo.production.hostname }}
          image: {{ .Values.odoo.image }}
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: {{ .Values.odoo.production.hostname }}-filestore
              mountPath: /var/lib/odoo  # Mounting the filestore
            - name: repo
              mountPath: /mnt/repos
            - name: extra-addons
              mountPath: /mnt/extra-addons
          env:
            - name: HOST
              value: kubegres
            - name: USER
              value: odoo
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
