apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-odoo
  namespace: {{ .Release.Namespace }}
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      volumes:
        - name: odoo-filestore
          persistentVolumeClaim:
            claimName: {{ .Values.odoo.filestore.pvcName }}
      containers:
        - name: odoo
          image: {{ .Values.odoo.image }}
          ports:
            - containerPort: 8069
          volumeMounts:
            - name: odoo-filestore
              mountPath: /var/lib/odoo  # Mounting the filestore
          env:
            - name: HOST
              value: kubegres
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
