odoo:
  image: "odoo:18"
  imageRegistry:
    url: ""
    username: ""
    password: ""
    email: ""
  domain: "odoo.bemade.org"
  production:
    hostname: "demo"
  filestore:
    size: ""
    storageClassName: "longhorn"
  # Database connection configuration
  database:
    host: ""
    port: 5432
    adminUser: "postgres"
    # Secret containing admin password
    # This secret will be copied from the adminSecretNamespace to the release namespace
    # as a secret named <release-name>-postgres-secret
    adminSecretName: "postgres-postgresql"
    # Namespace where the admin secret is located
    # If specified, RBAC resources will be created to allow reading the secret from this namespace
    # If not specified, the chart will look for the secret in the release namespace
    adminSecretNamespace: "postgres"
    # Key in the secret that contains the admin password
    adminPasswordKey: "postgres-password"
    pgpool:
      enabled: true
      adminPassword: ""
  ingress:
    enabled: true
    tlsSecretName: "odoo-tls-secret"
    clusterIssuer: "letsencrypt-dns"
  masterPassword: "$00p3rP4ssW0rD!"
  enterprise:
    enabled: false
    path: "/mnt/enterprise-addons"  # Path where enterprise addons are located in the image
  # Odoo configuration parameters
  conf:    
    limit_time_real: 600
    limit_time_cpu: 600
    workers: 2
  addonRepos:
    - name: "bemade-addons"
      url: "git@git.bemade.org:bemade/bemade-addons.git"
      branch: "18.0"
      commit: null
      sshAuth:
        secretName: "bemade-gitlab-ssh"
      passwordAuth:
        username: ""
        password: ""
      activeAddons:
        - name: caldav_sync
  repoStorage:
    size: ""
    storageClassName: "longhorn"
  # Affinity is set directly in the deployment template to target worker nodes by default.
  # To override this behavior, set useCustomAffinity to true and define your custom affinity below.
  affinity: {}