odoo:
  image: "odoo:18"
  imageRegistry:
    url: ""
    username: ""
    password: ""
    email: ""
  domain: "odoo.bemade.org"
  hostname: "demo"
  filestore:
    size: ""
    storageClassName: "longhorn"
  # Database configuration
  database:
    # PostgreSQL configuration
    postgresql:
      image: "postgres:16.1-alpine"
      persistence:
        enabled: true
        size: "10Gi"
        storageClassName: "longhorn"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      # PostgreSQL configuration
      config:
        max_connections: 100
        shared_buffers: "256MB"
      # Admin user configuration
  ingress:
    enabled: true
    tlsSecretName: "odoo-tls-secret"
    clusterIssuer: "letsencrypt-dns"
  masterPassword: "$00p3rP4ssW0rD!"
  enterprise:
    enabled: false
    path: "/mnt/enterprise-addons"  # Path where enterprise addons are located in the image
  # Odoo configuration parameters
  conf:    
    limit_time_real: 600
    limit_time_cpu: 600
    workers: 2
  affinity: {}