apiVersion: v1
kind: ConfigMap
metadata:
  name: addon-repos-json
  namespace: {{ .Release.Namespace }}
data:
  {{- range .Values.odoo.addonRepos }}
  {{ .name }}.json: {{ toPrettyJson (.) }}
  {{- end }}
