apiVersion: v1
kind: ConfigMap
metadata:
  name: test-scripts
  namespace: {{ .Release.Namespace }}
data:
  test-chart-installed.sh: {{ .Files.Get "files/tests/test-chart-installed.sh" | quote }}
  test-production-connectivity.sh: {{ .Files.Get "files/tests/test-production-connectivity.sh" | quote }}
