{{- if .Values.odoo.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: odoo-websocket
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.odoo.hostname  }}.{{ .Values.odoo.domain }}`) && PathPrefix(`/websocket`)
      middlewares:
        - name: remove-prefix
          namespace: {{ .Release.Namespace }}
      services:
        - kind: Service
          name: odoo-{{ .Values.odoo.hostname }}
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: 8072
          scheme: http
  tls:
    secretName: odoo-cert
{{- end }}
